### ISSUE TITLE
about NAN in the gradients

### ISSUE THREAD

**Issue by boxuLibrary** [WU-CVGL/BAD-NeRF#10]
hi, it's a excellent work. However, when i run my own dataset with the code. There will be NAN in the backward gradient. I checked the gradient graph. I found that the reason is that the rotation interpolation algorithm results in NAN in the rotation part of the estimated variables. Do you know why this happened? Thank you very much.

**Comment by LingzheZhao** [comment]
Hi, you can first try lowering the `pose_lrate`. And if the dataset that you are using is not captured in [LLFF style](https://github.com/Fyusion/LLFF?tab=readme-ov-file#using-your-own-input-images-for-view-synthesis), you need to disable the [NDC scene contraction option](https://github.com/WU-CVGL/BAD-NeRF/blob/aed2c4a4b2301f516b68245d035114826f20b0b7/run_nerf.py#L95).

In case you missed it BTW, we had a similar discussion here in this issue: #9 .

If the problem still happens, please provide more details about your problem, e.g., used dataset and settings like `pose_lrate` so we can dig into the problem together.
