### ISSUE TITLE
Checkpoint Problem

### ISSUE THREAD

**Issue by Wang-Wilson** [WU-CVGL/BAD-NeRF#11]
Thanks for your great work! I am trying to do experiments on your code. I am not familiar with the code now, so I am inquiring about some bugs.
I can load the weight you provided from the pre-trained model, but my PC accidentally shut down during the training. How can I start the training from my training checkpoint? I tried changing the weight_iter in configs to 220000, but it didn't work. However, when I change it back to 200000, It will start all over again.

The error is like:

Traceback (most recent call last):
  File "C:\Users\wilso\BAD-NeRF\train.py", line 324, in <module>
    train()
  File "C:\Users\wilso\BAD-NeRF\train.py", line 109, in train
    graph.load_state_dict(graph_ckpt['graph'])
  File "C:\Users\wilso\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Graph:
        Unexpected key(s) in state_dict: "se3_sharp.weight".

Do you have any idea about this?

**Comment by wangpeng000** [comment]
Sorry to reply late, I re-download the weights I provided here [weights](https://westlakeu-my.sharepoint.com/:f:/g/personal/cvgl_westlake_edu_cn/EsgdW2cRic5JqerhNbTsxtkBqy9m6cbnb2ugYZtvaib3qA?e=bjK7op) and run the code successfully. Have you changed something? You can find the saved parameters in line 239.
