### ISSUE TITLE
Equation 10-12 jacobians

### ISSUE THREAD

**Issue by xianrui-luo** [WU-CVGL/BAD-NeRF#6]
Hi, I wonder where is the corresponding code of equation 10-12 in the paper? My understanding is that it is simply a Jacobian representation, then what are these equations' role here in the paper?

**Comment by wangpeng000** [comment]
Yes, they are Jacobian matrice. We write these formulations to tell the reviewers the poses are differentiable.

**Comment by xianrui-luo** [comment]
Thank you for clarifying.
